In [5]:
#Task 3: Write an API call to the census API that gets data helpful for your table. If you can get it 
#into a dataframe that matches your schema that is great but time may preclude the full transformation.

#get census data
import pandas as pd

In [10]:
#for merging purposes
import requests
request_obj = requests.get('https://api.census.gov/data/2017/acs/acs5/?get=B01003_001E,B07011_001E,B15003_001E,B23025_005E,B17001_001E&for=state:*')
json = request_obj.json()
df_zip_info = pd.DataFrame(json)
df_zip_info.columns = ['total_population', 'median_income', 'education_attainment', 'employment_status', 'poverty_status', 'zipcode']

#df_zip_info['per_bl'] = df_zip_info['total_black'] / df_zip_info['total_population']

df_zip_info

#still need to id the most useful metrics and apply properly

,total_population,median_income,education_attainment,employment_status,poverty_status,zipcode
0,B01003_001E,B07011_001E,B15003_001E,B23025_005E,B17001_001E,state
1,3468963,None,2390791,220597,3437079,72
2,4850771,24476,3276637,165391,4729116,01
3,738565,32940,475442,29548,719983,02
4,6809946,27517,4516175,225911,6654096,04
5,2977944,23789,1985770,85128,2890095,05
6,38982847,29454,25950818,1491146,38242946,06
7,5436519,32401,3668477,152856,5316870,08
8,3594478,35326,2480297,140712,3486033,09
9,672391,43198,477843,31279,638362,11
10,943732,31560,651540,30245,918100,10
11,20278447,25952,14396066,699117,19858469,12
12,10201635,27024,6693826,372581,9931935,13
13,1421658,32453,984320,34380,1383246,15
14,1657375,25298,1065313,42328,1626557,16
15,12854526,30684,8666079,491310,12551822,17
16,6614418,27247,4369451,202199,6412384,18
17,3118102,30002,2067914,69018,3016358,19
18,2903820,29126,1886741,71009,2820265,20
19,4424376,24702,2986199,140717,4287887,21
20,1330158,26841,961086,36790,1294998,23
21,4663461,25086,3092069,157186,4531570,22
22,6789319,34498,4706536,224856,6552347,25
23,5996079,37147,4095427,198375,5856088,24
24,9925568,26987,6719972,361624,9698121,26
25,5490726,32734,3698605,130510,5366210,27
26,2986220,22766,1956101,117786,2890123,28
27,6075300,26999,4100209,175919,5891760,29
28,1029862,26249,703919,25076,1004612,30
29,1893921,30020,1233842,38881,1839825,31
30,1331848,33172,939471,33566,1289255,33
31,2887725,29019,1968023,116285,2846365,32
32,8960161,35075,6163699,328167,8783989,34
33,2084828,24457,1381630,73710,2043896,35
34,19798228,31057,13660809,685368,19285448,36
35,10052564,26482,6784048,352287,9783738,37
36,745475,32336,485490,11085,719722,38
37,11609756,27435,7888150,378735,11289161,39
38,3896251,26207,2553488,105375,3780828,40
39,4025127,27389,2797953,138139,3947954,41
40,12790505,28923,8885953,422016,12377251,42
41,1056138,30210,729261,38634,1015923,44
42,4893444,25454,3325601,170257,4751345,45
43,855444,28821,560605,17018,826297,46
44,6597381,25453,4478450,210756,6436601,47
45,27419612,28063,17454431,784888,26794198,48
46,2993941,27928,1743090,64314,2946717,49
47,624636,29351,437900,14969,600127,50
48,8365952,32545,5680765,236648,8116130,51
49,1836843,23707,1293665,57659,1784004,54
50,7169967,32318,4896055,218821,7037413,53
51,583200,30854,388617,14459,569412,56
52,5763217,29868,3907816,145271,5612611,55

In [12]:
df_zip_info.to_csv('data/us_census.csv')